### ISSUE TITLE
Summary not closed out correctly

### ISSUE THREAD

**Issue by dracon80** [jfelipearaujo/ClassBuilderGenerator#1]
Thanks for putting this together. Makes a good start on the process, but I've found a few issues with it.

The Summary isn't closed out correctly for the created documentation, you missing the closing slash.

It would also be great if there was an option to name the fields with a leading _ to stick to best practice.

**Comment by jfelipearaujo** [comment]
Hi @dracon80 , thank you for your message.

About the Summary, do you have an example of class that generated an wrong summary? So I'll be able to reproduce the error.

About the _, I'll be add an option for this.

**Comment by dracon80** [comment]
Hi @jfelipearaujo, My skill levels aren't up to doing a pull request just yet. But you can see in https://github.com/jfelipearaujo/ClassBuilderGenerator/blob/master/Core/SummaryHelper.cs that you aren't closing the summary tag on lines.
22, 45, 64, 96, 137,  & 174.  They should all be `.AppendLine("/// </summary>")` . You are just missing the /  in it.

**Comment by jfelipearaujo** [comment]
Hi @dracon80, I've just updated the extension with your suggestion about the "_" prefix and the bug reported.

Thank you so much for the help :)

**Comment by dracon80** [comment]
Awesome
