### ISSUE TITLE
typeparamref used instead of cref

### ISSUE THREAD

**Issue by dracon80** [jfelipearaujo/ClassBuilderGenerator#5]
On line 101 (and many others in the same class) 
https://github.com/jfelipearaujo/ClassBuilderGenerator/blob/bd8b3b9e80206904b22def4feef5888ae945140d/Core/SummaryHelper.cs#L101

you are using typeparamref to define the parameter type. Is there a reason for this that I'm not seeing? In all my classes I get a CS1735 warning as this tag is for referencing generic types.

Maybe there needs to be a check to see if the parameter is a generic type, and if not then use <see cref> instead?

**Comment by jfelipearaujo** [comment]
Okay, I'll think in something nice to do about this :)
