### ISSUE TITLE
Generator throws exception

### ISSUE THREAD

**Issue by KasparRugholmHenriksen** [jfelipearaujo/ClassBuilderGenerator#7]
While using the functionality on a given class the following error message is shown

![image](https://user-images.githubusercontent.com/113911101/191023276-3cd2ccc9-a68c-4a36-a86a-df951c2c0746.png)

1. Right click class file
2. Choose Run Class Builder Generator

**Expected behavior**
A builder class was generated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VS Version:  2022
 - Version 17.1.3

**Additional context**
This are the entries in the ActivityLog,xml for Visual Studio

  <entry>
    <record>788</record>
    <time>2022/09/19 13:00:53.517</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [ClassBuilderGeneratorPackage]</description>
    <guid>{A9F67D60-554C-47D0-AC07-FB09BB79088D}</guid>
  </entry>
  <entry>
    <record>789</record>
    <time>2022/09/19 13:00:53.536</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [ClassBuilderGeneratorPackage]Source: &apos;ClassBuilderGenerator&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at ClassBuilderGenerator.ClassBuilderGeneratorPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{A9F67D60-554C-47D0-AC07-FB09BB79088D}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by KasparRugholmHenriksen** [comment]
Forgot to mention that if you restart Visual Studio and follow the steps above again. Nothing happens. Nothing is generated and no error messages.

**Comment by jfelipearaujo** [comment]
@KasparRugholmHenriksen hi, thanks for share the error. Which version of the extension are you running? Did this error occur only once or does it happen all the time?

**Comment by KasparRugholmHenriksen** [comment]
No problem. Thanks for the extension. It is working fine on other machines except mine. I am using the latest version. It happens all of the time. I tried un-installing the extension a number of times, and also disable ReSharper in case there was anything here causing the issue. I tried installing the extension by downloading from the extension homepage, and also through the extension manager inside Visual Studio.

Please let me know if this is sufficient information

**Comment by jfelipearaujo** [comment]
@KasparRugholmHenriksen Sorry about my delay, I was investigating this issue and I have a guess. If you pay attention on error, it is possible notice the error is related with version **17.3.0.0** of Microsoft.VisualStudio.Threading and according to you your Visual Studio is running in version **17.1.3**, in other words you're using an old version of Visual Studio. Maybe you can try to update your Visual Studio to the latest version and try to use the extension again. Meanwhile I'll try to set a minimum version to run the extension and prevent this kind of error happens again. Let's keep in touch until this is solved.

**Comment by jfelipearaujo** [comment]
@KasparRugholmHenriksen I've figure out the problem and I just released a new version. Could you please download this new version and test again?

**Comment by KasparRugholmHenriksen** [comment]
@jfelipearaujo Thanks - that worked
